#!/bin/bash

pushd `dirname $0` > /dev/null
SCRIPTPATH=`pwd`
popd > /dev/null

cd $SCRIPTPATH

if [ $# -eq 0 ]
  then
    echo "Usage: gpm COMMAND"
    echo ""
    echo "Availible COMMANDs:"
    echo "  install PKG     # install a package"
    echo "  install-deps PKG # install the dependencies of a package"
    echo "  update          # update gpm"
    echo "  upgrade         # update all installed packages"
    echo "  upgradepkg PKG  # update only the package provided"
    echo "  status          # show the status of all packages"
    echo "  module PKG command # execute command in folder of module"
    exit
fi

if [ $1 = "update" ]; then
    git pull
    exit
fi

if [ $1 = "install" ]; then
    git clone https://github.com/GraphProgramming/$2.git
    cd $2
    ./install.sh
    exit
fi

if [ $1 = "install-deps" ]; then
    cd $2
    ./install-deps.sh
    exit
fi

if [ $1 = "module" ]; then
    cd $2
    echo ${@:3}
    ${@:3}
    exit
fi

if [ $1 = "upgradepkg" ]; then
    cd $2
    git pull
    cd ..
    exit
fi

if [ $1 = "upgrade" ]; then
    for dir in /$SCRIPTPATH/*/
    do
	dir=${dir%*/}
	dir=${dir##*/}
	if [ $dir = "images" ]; then
		continue
	fi
        cd $dir
	echo "Upgrading: $dir"
        git pull
	echo ""
        cd ..
    done
    exit
fi

if [ $1 = "status" ]; then
    echo "Status: GraphProgramming (meta-package)"
    git status
    echo ""
    for dir in /$SCRIPTPATH/*/
    do
	dir=${dir%*/}
	dir=${dir##*/}
	if [ $dir = "images" ]; then
		continue
	fi
        cd $dir
	echo "Status: $dir"
        git status
	echo ""
        cd ..
    done
    exit
fi

